baseURL = "https://mohdsaed.me"
languageCode = "en-us"
title = "Mohammed Saed"
theme = "mohdsaed-dark"

[params]
	author = "Mohammed Saed"
	description = "Mohammed Saed's blog on computers, programming, travel, and life."
	googleAnalytics = "G-M3PMJBEK4R"
