baseURL = "https://mohdsaed.me/"
languageCode = "en-us"
title = "Mohammed Saed"
theme = "mohdsaed-dark"
disqusShortname = "https-mohdsaed-me"
enableGitInfo = true

[params]
	author = "Mohammed Saed"
	description = "Mohammed Saed's blog about computers, programming, and life."
	googleAnalytics = "G-M3PMJBEK4R"

[markup]
	[markup.goldmark]
		[markup.goldmark.parser]
			[markup.goldmark.parser.attribute]
				block = true
